### ISSUE TITLE
Application should probably be renamed

### ISSUE THREAD

**Issue by f0s3** [f0s3/bluetooth_dmenu#4]
The idea of this app came from connman_dmenu, which uses connmanctl as its backend. 
Thus I recon to rename bluetoothctl_dmenu to bluetooth_dmenu to keep it consistent.

TL;DR
Expected:
connman_dmenu - > connmanctl, so
bluetooth_dmenu -> bluetoothctl
Now:
bluetooth**ctl**_dmenu

**Comment by Ar4ys** [comment]
Nice idea, I have done it #6
